jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Go get
        run: go get -v -t -d ./...

      - name: Go test
        run: go test -v ./...

name: Run Tests
on:
  push:
